# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require 'json'

opt_out_usage

default_platform(:ios)

pods = [
  "AppSyncRealTimeClient.podspec"
]

platform :ios do
  desc "Bump pod versions"
  lane :bump_podspecs_patch do

    pods.each { |pod| version_bump_podspec(path: pod, bump_type: "patch") }

  end

  desc "Release pods"
  lane :release_pods do
    # Define `COCOAPODS_TRUNK_TOKEN` env var for trunk authentication
    # https://github.com/CocoaPods/cocoapods-trunk/commit/9e6ec1c1faf96fa837dc2ed70b5f54006b181ed6
    secret = sh(
        command: 'aws secretsmanager get-secret-value --secret-id ${COCOAPODS_SECRET_ARN}',
        log: false
    )

    ENV['COCOAPODS_TRUNK_TOKEN'] = JSON.parse(secret)["SecretString"]

    pods.each { |pod|
      pod_push(path: pod, allow_warnings: true, swift_version: "5.1")
      Actions.sh('pod repo update')
    }

  end

end
