name: Build and Test
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
      contents: read

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-test-ios:
    runs-on: macos-12
    steps:
      - name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          persist-credentials: false

      - name: Restore Gems Cache
        uses: actions/cache/restore@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: vendor/bundle
          key: app-${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            app-${{ runner.os }}-gems-

      - name: Install Bundle
        env:
          BUNDLE_PATH: vendor/bundle
        run: |
            bundle config set --local path $BUNDLE_PATH
            bundle check || bundle install

      - name: Install Pods
        run: |
          bundle exec pod install

      - name: Test AppSyncRealTimeClient
        run: xcodebuild test -workspace AppSyncRealTimeClient.xcworkspace -scheme AppSyncRealTimeClient -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14,OS=latest" | xcpretty --simple --color --report junit && exit ${PIPESTATUS[0]}